name: 'Create Environment'
description: 'Create or Update conda environment using environment.yml and install Poetry project using pyptoject.toml'
inputs:
  github_token:
    description: 'GitHub API Access Token'
    default: ${{ github.token }}
    required: false
  repository:
    description: 'GitHub Repository name'
    default: ${{ github.event.repository.name }}
    required: false

runs:
  using: "composite"

  steps:
    - name: Cache conda
      uses: actions/cache@v2
      env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
        CACHE_NUMBER: "0"
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

    - name: Cache Env Installation
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        channels: conda-forge
        use-only-tar-bz2: true  # IMPORTANT: This needs to be set for caching to work properly!
        activate-environment: ${{ github.event.repository.name }}
        environment-file: environment.yml
        auto-activate-base: false

#    - name: Poetry Cache
#      uses: actions/setup-python@v4
#      with:
#        python-version: '3.8'
#        cache: 'poetry'

    - name: Install poetry dependencies
      shell: bash
      run: poetry install
