name: Production Validation Pipeline

# Controls when the workflows will run
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches: [ develop ]
  
  # Allows you to run these workflows manually from the Actions tab
  workflow_dispatch:
  
# A workflows run is made up of one or more jobs that can run sequentially or in parallel
jobs:

########### JOB 1 - Unit Tests and Code Coverage ###############################
  run-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
#    needs: setup-runner
    
    permissions:
      checks: write
      pull-requests: write  # only needed unless run with comment_mode: off
      #contents: read  # only needed for private repository
      #issues: read  # only needed for private repository

    steps:

      - name: Download Repository
        uses: actions/checkout@v2

      - name: Run PyTest
        uses: ./.github/actions/pytest


########### JOB 2 - Static code analysis ###############################
  static-code-analysis:
    runs-on: ubuntu-latest
#    needs: setup-runner

    steps:
      - name: Download Repository
        uses: actions/checkout@v2

      - name: static code analysis
        uses:  ./.github/actions/mypy
