name: Production Validation Pipeline

# Controls when the workflows will run
on:

  pull_request:
    types:
      - opened
      - synchronize
    branches: [ develop ]
  
  # Allows you to run these workflows manually from the Actions tab
  workflow_dispatch:
  
# A workflows run is made up of one or more jobs that can run sequentially or in parallel
jobs:

############ JOB 1 - Setup Runner ###############################################
#  setup-runner:
#    defaults:
#      run:
#        shell: bash -el {0}
#    name: Setup Runner
#    runs-on: ubuntu-latest
#    # WE ARE NOT USING ANY CONTAINER FOR NOW -- RUNNING ON THE HOST
#    # container: node:latest
#
#    # Setup runner host
#    steps:
#      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#      - name: Download Repository
#        uses: actions/checkout@v2
#
#      - name: Setup Conda Environment
#        uses: ./.github/actions/env-create


########### JOB 1 - Unit Tests and Code Coverage ###############################
  run-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: setup-runner
    
    permissions:
      checks: write
      pull-requests: write  # only needed unless run with comment_mode: off
      #contents: read  # only needed for private repository
      #issues: read  # only needed for private repository


    steps:

      - name: Download Repository
        uses: actions/checkout@v2


      - name: Run PyTest
        uses: ./.github/actions/pytest

#      - name: Run PyTest
#        run: |
#          PACKAGE_NAME=$(ls src | head -n 1)
#          python -m pytest --cov=src/$PACKAGE_NAME --cov-report xml tests/ --junitxml=out_report.xml
#
#      - name: Check PyTest Output
#        if: always()
#        run: |
#          cat out_report.xml
#          cat coverage.xml
#
#      - name: Publish Coverage Report
#        uses: AILAB-bh/gh-actions@coverage-comment--1.0.0
#        if: always()
#        with:
#          coverage_report: "coverage.xml"
#
#      - name: Publish Test Results
#        uses: AILAB-bh/gh-actions@publish-unit-test-results--2.0.0
#        if: always()
#        with:
#          junit_files: "out_report.xml"



########### JOB 2 - Static code analysis ###############################
  static-code-analysis:
    runs-on: ubuntu-latest
    needs: setup-runner
    
    steps:
      - name: Download Repository
        uses: actions/checkout@v2

      - name: static code analysis
        uses:  ./.github/actions/mypy
